2022-06-28 03:42:35.001 | INFO     | __main__:<module>:21 - Start script
2022-06-28 03:42:37.818 | INFO     | __main__:get_first_data:82 - Import Complite
2022-06-28 03:49:28.915 | DEBUG    | __main__:start_handler:174 - User №471485149 send I'm working)
2022-06-28 03:49:36.290 | INFO     | __main__:start_handler:183 - User №471485149 send No records
2022-06-28 03:56:28.313 | INFO     | __main__:<module>:21 - Start script
2022-06-28 03:57:32.018 | INFO     | __main__:get_first_data:82 - Import Complite
2022-06-28 04:05:16.608 | INFO     | __main__:<module>:21 - Start script
2022-06-28 04:06:20.636 | INFO     | __main__:get_first_data:82 - Import Complite
2022-06-28 04:17:54.091 | INFO     | __main__:check_old_data:146 - coin                            HNTUSDT
price                       10.85000000
quantity                 39157.23000000
dt           2022-06-28 04:05:50.115692
dt_resend    2022-06-28 04:17:53.496925
in_range                              1
Name: 4, dtype: object -0.0018433179723502668)
2022-06-28 04:22:54.006 | INFO     | __main__:check_old_data:146 - coin                            HNTUSDT
price                       10.85000000
quantity                 37763.48000000
dt           2022-06-28 04:05:50.115692
dt_resend    2022-06-28 04:22:53.720101
in_range                              1
Name: 4, dtype: object -0.0009216589861751334)
2022-06-28 04:27:56.602 | INFO     | __main__:check_old_data:146 - coin                            HNTUSDT
price                       10.85000000
quantity                 32210.47000000
dt           2022-06-28 04:05:50.115692
dt_resend    2022-06-28 04:27:54.171692
in_range                              1
Name: 4, dtype: object -0.0009216589861751334)
2022-06-28 04:30:23.526 | INFO     | __main__:start_handler:181 - User №471485149 send No records
2022-06-28 04:32:54.356 | INFO     | __main__:check_old_data:146 - coin                            HNTUSDT
price                       10.85000000
quantity                 29056.06000000
dt           2022-06-28 04:05:50.115692
dt_resend    2022-06-28 04:32:54.232552
in_range                              1
Name: 4, dtype: object -0.0)
2022-06-28 04:33:12.179 | INFO     | __main__:start_handler:189 - User №471485149 send all_verified_record
2022-06-28 04:33:15.365 | INFO     | __main__:start_handler:189 - User №471485149 send all_verified_record
2022-06-28 04:33:22.175 | INFO     | __main__:start_handler:189 - User №471485149 send all_verified_record
2022-06-28 04:33:32.052 | INFO     | __main__:start_handler:189 - User №471485149 send all_verified_record
2022-06-28 04:33:39.462 | INFO     | __main__:start_handler:189 - User №471485149 send all_verified_record
2022-06-28 04:33:47.113 | INFO     | __main__:start_handler:189 - User №471485149 send all_verified_record
2022-06-28 04:33:54.661 | INFO     | __main__:start_handler:189 - User №471485149 send all_verified_record
2022-06-28 04:34:00.135 | INFO     | __main__:start_handler:189 - User №471485149 send all_verified_record
2022-06-28 04:34:05.885 | INFO     | __main__:start_handler:189 - User №471485149 send all_verified_record
2022-06-28 04:34:09.341 | INFO     | __main__:start_handler:189 - User №471485149 send all_verified_record
2022-06-28 04:34:20.288 | INFO     | __main__:start_handler:189 - User №471485149 send all_verified_record
2022-06-28 04:34:30.808 | INFO     | __main__:start_handler:189 - User №471485149 send all_verified_record
2022-06-28 04:37:32.912 | INFO     | __main__:start_handler:181 - User №471485149 send No records
2022-06-28 04:38:24.081 | INFO     | __main__:start_handler:181 - User №471485149 send No records
2022-06-28 04:39:29.386 | INFO     | __main__:start_handler:181 - User №471485149 send No records
2022-06-28 04:40:22.607 | INFO     | __main__:start_handler:181 - User №471485149 send No records
2022-06-28 04:49:17.234 | INFO     | __main__:<module>:21 - Start script
2022-06-28 04:49:33.685 | INFO     | __main__:<module>:21 - Start script
2022-06-28 04:49:36.195 | DEBUG    | __main__:get_first_data:83 - Import Complite
2022-06-28 04:50:18.918 | INFO     | __main__:<module>:21 - Start script
2022-06-28 04:50:21.719 | DEBUG    | __main__:get_first_data:83 - Import Complite
2022-06-28 04:50:29.347 | DEBUG    | __main__:start_handler:180 - User №471485149 send I'm working
2022-06-28 04:50:29.366 | DEBUG    | __main__:start_handler:180 - User №471485149 send I'm working
2022-06-28 04:50:41.121 | INFO     | __main__:<module>:21 - Start script
2022-06-28 04:50:43.864 | DEBUG    | __main__:get_first_data:83 - Import Complite
2022-06-28 04:50:54.541 | DEBUG    | __main__:start_handler:180 - User №471485149 send I'm working
2022-06-28 07:41:24.948 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2022-06-28 07:41:47.034 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5276441681:AAHi9DX8ZYWVlm49AEBU1be0gVEXWmeKoZ8/getUpdates?offset=575910529&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213A39EA200>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-06-28 07:41:57.056 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5276441681:AAHi9DX8ZYWVlm49AEBU1be0gVEXWmeKoZ8/getUpdates?offset=575910529&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213A39EB340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-06-28 07:42:07.111 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5276441681:AAHi9DX8ZYWVlm49AEBU1be0gVEXWmeKoZ8/getUpdates?offset=575910529&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213A3C48250>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-06-28 07:49:30.507 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2022-06-28 07:49:40.578 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5276441681:AAHi9DX8ZYWVlm49AEBU1be0gVEXWmeKoZ8/getUpdates?offset=575910529&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213A3C4A350>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-06-28 07:49:50.596 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5276441681:AAHi9DX8ZYWVlm49AEBU1be0gVEXWmeKoZ8/getUpdates?offset=575910529&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213A3C4B370>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-06-28 08:00:22.805 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2022-06-28 08:00:32.846 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5276441681:AAHi9DX8ZYWVlm49AEBU1be0gVEXWmeKoZ8/getUpdates?offset=575910529&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213A3C6D420>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-06-28 08:00:42.875 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5276441681:AAHi9DX8ZYWVlm49AEBU1be0gVEXWmeKoZ8/getUpdates?offset=575910529&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213A3C6E3E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-06-28 08:11:05.573 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2022-06-28 08:11:27.634 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5276441681:AAHi9DX8ZYWVlm49AEBU1be0gVEXWmeKoZ8/getUpdates?offset=575910529&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213A3C6FD60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-06-28 08:11:37.665 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5276441681:AAHi9DX8ZYWVlm49AEBU1be0gVEXWmeKoZ8/getUpdates?offset=575910529&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213A3C9D4E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-06-28 08:11:47.778 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5276441681:AAHi9DX8ZYWVlm49AEBU1be0gVEXWmeKoZ8/getUpdates?offset=575910529&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213A3C9E5F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-06-28 08:34:56.111 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2022-06-28 08:35:18.224 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5276441681:AAHi9DX8ZYWVlm49AEBU1be0gVEXWmeKoZ8/getUpdates?offset=575910529&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213A3CC86A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-06-28 08:35:28.264 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5276441681:AAHi9DX8ZYWVlm49AEBU1be0gVEXWmeKoZ8/getUpdates?offset=575910529&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213A3CC95A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-06-28 08:35:38.288 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5276441681:AAHi9DX8ZYWVlm49AEBU1be0gVEXWmeKoZ8/getUpdates?offset=575910529&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213A3CCA6B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-06-28 08:36:00.366 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5276441681:AAHi9DX8ZYWVlm49AEBU1be0gVEXWmeKoZ8/getUpdates?offset=575910529&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213A3CCB5B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-06-28 08:36:10.407 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5276441681:AAHi9DX8ZYWVlm49AEBU1be0gVEXWmeKoZ8/getUpdates?offset=575910529&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213A4CC8760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-06-28 08:36:20.494 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5276441681:AAHi9DX8ZYWVlm49AEBU1be0gVEXWmeKoZ8/getUpdates?offset=575910529&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213A4CC9630>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-06-28 08:36:30.531 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5276441681:AAHi9DX8ZYWVlm49AEBU1be0gVEXWmeKoZ8/getUpdates?offset=575910529&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213A4CCA770>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-06-28 08:36:52.616 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5276441681:AAHi9DX8ZYWVlm49AEBU1be0gVEXWmeKoZ8/getUpdates?offset=575910529&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213A4CCB5B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-06-28 08:37:02.634 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5276441681:AAHi9DX8ZYWVlm49AEBU1be0gVEXWmeKoZ8/getUpdates?offset=575910529&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213A4CF0760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-06-28 08:37:12.679 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5276441681:AAHi9DX8ZYWVlm49AEBU1be0gVEXWmeKoZ8/getUpdates?offset=575910529&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213A4CF1630>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-06-28 08:37:22.716 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5276441681:AAHi9DX8ZYWVlm49AEBU1be0gVEXWmeKoZ8/getUpdates?offset=575910529&timeout=20 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000213A4CF2770>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-06-28 12:16:19.197 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2022-06-28 13:01:14.968 | INFO     | __main__:start_handler:189 - User №471485149 send No records
2022-06-28 13:02:32.011 | INFO     | __main__:<module>:21 - Start script
2022-06-28 13:02:33.529 | DEBUG    | __main__:get_first_data:83 - Import Complite
2022-06-28 13:02:46.361 | INFO     | __main__:<module>:21 - Start script
2022-06-28 13:03:47.741 | DEBUG    | __main__:get_first_data:83 - Import Complite
2022-06-28 13:06:21.070 | ERROR    | __main__:polling:172 - HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
2022-06-28 14:01:56.116 | INFO     | __main__:<module>:21 - Start script
2022-06-28 14:02:41.618 | DEBUG    | __main__:get_first_data:83 - Import Complite
2022-06-28 14:27:49.513 | INFO     | __main__:<module>:21 - Start script
2022-06-28 14:29:01.218 | DEBUG    | __main__:get_first_data:83 - Import Complite
2022-06-28 14:29:03.761 | INFO     | __main__:check_old_data:146 - coin                            ADAUSDT
price                        0.48870000
quantity                842426.50000000
dt           2022-06-28 14:27:52.517252
dt_resend    2022-06-28 14:29:03.258862
in_range                              1
Name: 0, dtype: object -0.004804972375690442)
2022-06-28 14:29:04.298 | INFO     | __main__:check_old_data:146 - coin                            ADAUSDT
price                        0.48760000
quantity                679346.70000000
dt           2022-06-28 14:27:52.523258
dt_resend           1970-01-01 00:00:00
in_range                              0
Name: 1, dtype: object -0.0070717596390483806)
2022-06-28 14:29:04.640 | INFO     | __main__:check_old_data:146 - coin                            ADAUSDT
price                        0.49440000
quantity                685538.70000000
dt           2022-06-28 14:27:52.526260
dt_resend           1970-01-01 00:00:00
in_range                              0
Name: 2, dtype: object 0.006779550970873793)
2022-06-28 14:29:04.869 | INFO     | __main__:check_old_data:146 - coin                            ADAUSDT
price                        0.49460000
quantity                805744.70000000
dt           2022-06-28 14:27:52.528262
dt_resend           1970-01-01 00:00:00
in_range                              0
Name: 3, dtype: object 0.007181176708451198)
2022-06-28 14:29:05.113 | INFO     | __main__:check_old_data:146 - coin                           AVAXUSDT
price                       19.61000000
quantity                 15831.06000000
dt           2022-06-28 14:28:01.301967
dt_resend           1970-01-01 00:00:00
in_range                              0
Name: 5, dtype: object -0.004280034166241675)
2022-06-28 14:29:05.308 | INFO     | __main__:check_old_data:146 - coin                           AVAXUSDT
price                       19.89000000
quantity                 18247.32000000
dt           2022-06-28 14:28:01.305971
dt_resend           1970-01-01 00:00:00
in_range                              0
Name: 6, dtype: object 0.009857643539467165)
2022-06-28 14:29:30.809 | INFO     | __main__:<module>:21 - Start script
2022-06-28 14:30:42.073 | DEBUG    | __main__:get_first_data:83 - Import Complite
2022-06-28 14:34:37.615 | INFO     | __main__:<module>:21 - Start script
2022-06-28 14:34:56.162 | INFO     | __main__:<module>:21 - Start script
2022-06-28 14:35:40.051 | INFO     | __main__:<module>:21 - Start script
